services:
  - type: web
    name: sakro-nestjs-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: URL
        value: https://sakro-nestjs-apis-8ln1.onrender.com/
      - key: whiteListedExtensions
        value: .jpg,.jpeg,.png,.gif,.mp4,.mov,.avi,.pdf,.doc,.docx,.txt,.m4a,.wav,.mp3
      - key: CLOUDINARY_CLOUD_NAME
        value: jqimomzw
      - key: CLOUDINARY_API_KEY
        value: "828366476286331"
      - key: CLOUDINARY_API_SECRET
        value: jZF8-zWR1_Wgps6RWL4tcPkyRO0
