services:
  - type: web
    name: sakro-nestjs-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: URL
        value: https://sakro-nestjs-apis-8ln1.onrender.com/
